# Generated by Django 6.0.4 on 2026-05-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_add',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_add',
            new_name='updated_at',
        ),
    ]
